stages:
  - Build
  - Test
  - Package
  - Release

variables:
  # Docker Image values
  DOCKER_IMAGE_NAME: "dikumud"
  DOCKER_BUILD_IMAGE: "$CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME"


##
## STAGE: Build Jobs
##


# Compile System
#
# Build the whole system and store what we need as artifacts for future
# jobs.
#
Compile:
  stage: Build
  tags:
    - Debian
  script:
    - cmake -DDIKU_STATIC=1 .
    - make all -j12

  artifacts:
    paths:
      - docs/
      - vme/bin/
      - vme/etc/
      - vme/include/
      - vme/lib/
      - vme/zone/*.zon
      - vme/www/


##
## STAGE: Package Jobs
##


#
# Image Build Template.
#
# Job template to build the Docker containers from the project Dockerfiles
# and push them into the container repository.
#
# The following variables need to be set for this template to operate:
#
#   BUILD_TAG     THe digest tag to add to the image.
#                   Generally this will be Commit SHA ($CI_COMMIT_SHA)
#   DOCKER_ARGS   Any arguments that need to be passed to the Docker build
#                 process.
#
.build_image:
  stage: Package
  tags:
    - Docker

  before_script:
    # docker wants the password to be passed via stdin for security
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  
  script:
    # fetch the lastest image to speed up build
    - docker pull $DOCKER_BUILD_IMAGE:latest || true

    # build the container and push it into the registry
    - >
      docker build
      --pull
      --cache-from $DOCKER_BUILD_IMAGE:latest
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$BUILD_TAG"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $DOCKER_BUILD_IMAGE:$BUILD_TAG
      $DOCKER_ARGS
      .
    - docker push $DOCKER_BUILD_IMAGE:$BUILD_TAG


DikuMUD:
  extends: .build_image
  variables:
    BUILD_TAG: '$CI_COMMIT_SHA'
    DOCKER_ARGS: ""


##
## STAGE: Release Jobs
##


#
# Image Release Template.
#
# Job template to apply meaningful tags to images within the container
# registry. Takes the current pipelines commit SHA image and then pushes
# a new image with the digest tag provided in $RELEASE_TAG.
#
# The following variables need to be set for this template to operate:
#
#   DOCKER_IMAGE_NAME     The name of the image to be released.
#   RELEASE_TAG           The digets tag to apply to the released image.
#
.release_image:
  stage: Release
  tags:
    - Docker
  variables:
    # we do not need GitLab to clone the source code.
    GIT_STRATEGY: none
  before_script:
    # docker wants the password to be passed via stdin for security
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker pull $DOCKER_BUILD_IMAGE:$BUILD_TAG
    - docker tag $DOCKER_BUILD_IMAGE:$BUILD_TAG $DOCKER_BUILD_IMAGE:$RELEASE_TAG
    - docker push $DOCKER_BUILD_IMAGE:$RELEASE_TAG


# Release: Latest Image
#
# Any commits to the default branch in the project will be released as the
# "latest" image.
DikuMUD-latest:
  extends: .release_image
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    BUILD_TAG: '$CI_COMMIT_SHA'
    RELEASE_TAG: 'latest'


# Release: Release Tag
#
# When Releases are created, the commit will be given the Tag associated with
# the release in $CI_COMMIT_REF_NAME. We will create a image in the container
# registry with the Release Tag as the images digest tag.
DikuMUD-tag:
  extends: .release_image
  only:
    - tags
  variables:
    BUILD_TAG: '$CI_COMMIT_SHA'
    RELEASE_TAG: '$CI_COMMIT_REF_NAME'


Pages Docs:
  stage: Release
  script:
    # TODO: We need to actually build the documentation here ideally.
    #
    # Copy documentation to pages (clean out any existing documentation first)
    - rm -rf public
    - mv -f docs public
  pages: true
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
