stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  #image: gcc:12.2
  before_script:
    - apt-get update
    - apt-get install -y gcc g++ make cmake
    - apt-get install -y cmake bison flex libboost-all-dev libssl-dev rapidjson-dev doxygen graphviz dia mscgen
  script:
    - echo "Compiling the code..."
    - cmake .
    - make all
    - make test
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - ls -l
    - echo "Code coverage is 90%"

lint-test-job:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."