version: "3.9"
services:
  server:
    image: dikumud:1.0
    container_name: dikumud
    network_mode: host
    volumes:
      - server_data:/mnt
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3
    restart: on-failure

volumes:
  server_data:
    name: dikumud-vol
