apiVersion: apps/v1
kind: Deployment
metadata:
  name: dikumud
  labels:
    app.kubernetes.io/name: dikumud
    app.kubernetes.io/instance: dikumud-prod
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: dikumud
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dikumud
      app.kubernetes.io/instance: dikumud-prod
      app.kubernetes.io/component: server
      app.kubernetes.io/part-of: dikumud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dikumud
        app.kubernetes.io/instance: dikumud-prod
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: dikumud
    spec:
      containers:
        - name: dikumud
          image: registry.core.dunbart.net/mud/dikumud4/dikumud:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: dikumud-players
              mountPath: /vme/data/players
          ports:
            - name: telnet
              containerPort: 4242
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
        - name: dikumud-players
          persistentVolumeClaim:
            claimName: dikumud-players-pvc
